# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28b740ef4c7d3ce26976b83102b9eecdba007c5c8cced3d7a8ea3bcaac343bfefdd67c787dc1cff3f5cc330a70b44e7ba11a2c611ad1bde2cbf61b0ccf1af79c

test:
  secret_key_base: 20370a28f75115bf3a84b54f60dd99556044a448eb1a3c12126aa85e58bfaa4fc1e61e81777baaba58be055e312d8a7745b68fe58474425d840ee5a19d333287

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
